# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [13]:
import numpy as np
import itertools
import math
import functools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def check_input():
    '''
    The function check the values entered from the console
    '''
    check = False
    while not check:
        i = int(input("Enter matrix size: "))
        if i > 0:
            check = True
        else:
            print("Enter correct data: ")
    return i


def permutate_list(size, matrix):
    '''
    The function of creating a list of matrix element permutation
    '''

    reshuffle = math.factorial(size)
    
    arr = []
    list_of_sign = []
    permutate_list = []
    
    for i in range(size):
        arr.append(str(i))

    arr = tuple(map(int, arr))
    tmp = list(itertools.permutations(arr, size))
    tmp = list(map(list, tmp))

    for elem in tmp:
        count = 0
        index = 1

        for i in range(len(elem)):
            for s in range(i):
                if elem[s] > elem[i]:
                    count += 1

        if count % 2 == 0 or count == 0:
            list_of_sign.append(index)
        else:
            list_of_sign.append((-1)*(index))
    
    for j in range(reshuffle):
        intermediate_list = []   

        for i in range(size):
            intermediate_list.append(matrix[i][tmp[j][i]])

            if i == 0:
                intermediate_list[0] = intermediate_list[0] * list_of_sign[j]
            if i == size - 1:
                permutate_list.append(intermediate_list)

    return permutate_list


def calculation_of_product(permutate_list):
    '''
    This function works with inversions and performs a multiplication operation
    '''
    calculation_of_product=[]
    for el in permutate_list:
        calculation_of_product.append(functools.reduce(lambda a,b: a*b,el))
    return calculation_of_product

 
def general_sum(calculation_of_product):
    '''
    This function collects results together
    '''
    general_sum = sum(calculation_of_product)
    return general_sum


size = check_input()
matrix = random_matrix(size)

print(matrix)
print('-' * 80)

print("det A = ", general_sum(calculation_of_product(permutate_list(size, matrix))))

[[6 1 9]
 [4 6 8]
 [5 8 3]]
--------------------------------------------------------------------------------
det A =  -230
